[workspace]
members = [
    "common", "compiler", "machine", 
    "parser",
    "scanner",
]

[features]
trace = ["machine/trace"]
stress_gc = ["machine/stress"]
typecheck = ["parser/debug"]
dump = ["compiler/dump"]
debug = ["trace", "stress_gc", "dump", "common/debug", "typecheck"]

[package]
name = "zero"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "common" }
scanner = { path = "scanner" }
parser = { path = "parser" }
compiler = { path = "compiler" }
machine = { path = "machine" }
clap = { version = "4.5", features = ["derive"] }
rmp-serde = "1.3.0"

[dev-dependencies]
criterion = "0.5"
rustc-hash = "*"

[[bench]]
name = "language_benchmarks"
harness = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
# split-debuginfo = "packed"
# strip = "debuginfo"
debug = 1
