[workspace]
resolver = "3"
members = [ "common", "compiler", "machine", "parser", "reporting"]

[package]
name = "coil"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "common" }
machine = { path = "machine" }
parser = { path = "parser" }
compiler = { path = "compiler" }
reporting = { path = "reporting" }
rkyv = "0.8.12"
semver = "1"

[dev-dependencies]
criterion = { version = "^0.8", features = ["html_reports"] }

[[bench]]
name = "fib"
harness = false

[features]
default = []

[profile.release]
opt-level=3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
# debug = 1

[profile.branch_misses]
inherits="release"
debug = 2
