[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[features]
pratt = []

[dependencies]
common = { path = "../common" }
machine = { path = "../machine" }
parser = { path = "../parser" }
reporting = { path = "../reporting" }
rkyv = "0.8.12"

[dev-dependencies]
machine = { path = "../machine", features = ["vm_profile"] }
