[package]
name = "machine"
version = "0.1.0"
edition = "2024"

[features]
trace = []
stress = []

[dependencies]
ahash = "0.8.11"
common = { path = "../common" }
gc = { version = "0.5.0", features = ["derive"] }
generational-arena = "0.2.9"
libffi = "4.0.0"
libloading = "0.8.6"
parser = { path = "../parser" }
rustc-hash = { version = "2.1.1", features = ["rand"] }
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
